# Generated by Django 4.2.1 on 2023-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy_year', models.IntegerField()),
                ('time_duration', models.IntegerField()),
                ('price', models.FloatField()),
                ('policy_type', models.CharField(choices=[('Health Insurance', 'Health Insurance'), ('Life Insurance', 'Life Insurance'), ('Car Insurances', 'Car Insurances')], max_length=100)),
            ],
        ),
    ]
