# Generated by Django 4.2.1 on 2023-05-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
