# Generated by Django 4.2.1 on 2023-05-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='Insurance',
            new_name='insurance_i',
        ),
        migrations.RenameField(
            model_name='purchases',
            old_name='User',
            new_name='user_i',
        ),
    ]
